// FOOTBALL POSTER AI BOT - SAFE - Key only in your browser
let GROQ_KEY = localStorage.getItem('groq_key') || "";
const DB={news:["BREAKING: {team} in talks to sign {player} for {price}M","DONE DEAL: {player} to {team} confirmed"],banter:["Man Utd fans after 1 win: We are back - still 11th btw","Arsenal: This is our year - every year since 2004","Chelsea spent 1B to be midtable"],stats:["Haaland {g} goals in {m} games"]};
const teams=["Arsenal","Man Utd","Chelsea","Liverpool","Man City","Barca","Real Madrid"],players=["Mbappe","Haaland","Saka","Bellingham","Salah"],R=a=>a[Math.floor(Math.random()*a.length)],RN=(a,b)=>Math.floor(Math.random()*(b-a+1))+a;
function base(t){let x=R(DB[t]);return x.replace(/{team}/g,R(teams)).replace(/{player}/g,R(players)).replace("{price}",RN(30,150)).replace("{g}",RN(5,25)).replace("{m}",RN(5,15));}
async function aiRewrite(txt){
 if(!GROQ_KEY){let k=prompt("🔑 Paste your Groq API Key (gsk_...):\nSaved ONLY in your phone"); if(k){localStorage.setItem('groq_key',k.trim()); GROQ_KEY=k.trim();} else return txt+" 🔥";}
 try{const r=await fetch("https://api.groq.com/openai/v1/chat/completions",{method:"POST",headers:{"Authorization":"Bearer "+GROQ_KEY,"Content-Type":"application/json"},body:JSON.stringify({model:"llama-3.1-8b-instant",messages:[{role:"system",content:"You are viral African football banter admin. Rewrite funny short with emojis. Max 22 words."},{role:"user",content:txt}],max_tokens:80})}); const d=await r.json(); return d.choices[0].message.content.trim();}catch(e){return txt+" 😂";}
}
const sched=[{h:7,t:"news"},{h:10,t:"banter"},{h:13,t:"news"},{h:16,t:"stats"},{h:19,t:"banter"},{h:21,t:"news"},{h:23,t:"banter"}];
async function checkPost(){const now=new Date(),camHour=(now.getUTCHours()+1)%24,today=now.toDateString(); let posted=JSON.parse(localStorage.getItem('postedHours')||'[]'); if(localStorage.getItem('lastPostDay')!==today) posted=[]; for(let s of sched){if(camHour>=s.h &&!posted.includes(s.h)){let raw=base(s.t); let finalText=await aiRewrite(raw); let newPost={ty:s.t,tg:s.t.toUpperCase(),tt:finalText,em:"🔥",tm:"now",lk:RN(1,9)+"."+RN(1,9)+"K",cm:RN(100,900)+""}; if(typeof data!=='undefined'){data.unshift(newPost); if(typeof load==='function') load();} posted.push(s.h); localStorage.setItem('postedHours',JSON.stringify(posted)); localStorage.setItem('lastPostDay',today); break;}}}
setInterval(checkPost,60000); checkPost();
